INFO:     127.0.0.1:33444 - "GET /api/users/5148d5b0-9924-4308-8626-d0d0399cb351/robot-requests HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 803, in _literal_coercion
    return expr._bind_param(operator, element, type_=bindparam_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 4624, in _bind_param
    return BindParameter(
           ^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 2043, in __init__
    self.type = _compared_to_type.coerce_compared_value(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/type_api.py", line 1059, in coerce_compared_value
    _coerced_type = _resolve_value_to_type(value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/sqltypes.py", line 3889, in _resolve_value_to_type
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Object <app.models.user.User object at 0x74489c955520> is not legal as a SQL literal value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/app/routers/user.py", line 46, in get_user_robot_requests
    current_user = db.query(User).filter(User.id == current_user_id).first()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/operators.py", line 584, in __eq__
    return self.operate(eq, other)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 453, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/operators.py", line 584, in __eq__
    return self.operate(eq, other)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/orm/properties.py", line 479, in operate
    return op(self.__clause_element__(), *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/annotation.py", line 371, in __eq__
    return self.__element.__class__.__eq__(self, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/operators.py", line 584, in __eq__
    return self.operate(eq, other)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 1523, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/operators.py", line 584, in __eq__
    return self.operate(eq, other)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/type_api.py", line 212, in operate
    return op_fn(self.expr, op, *other, **addtl_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/default_comparator.py", line 121, in _boolean_compare
    obj = coercions.expect(
          ^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 395, in expect
    resolved = impl._literal_coercion(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 805, in _literal_coercion
    self._raise_for_expected(element, err=err)
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 784, in _raise_for_expected
    return super()._raise_for_expected(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stanley/tradewizard-bazaar/backend/venv/lib/python3.12/site-packages/sqlalchemy/sql/coercions.py", line 518, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: SQL expression element or literal value expected, got <app.models.user.User object at 0x74489c955520>.